services:
  - type: web
    name: softbank-1
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tradehub.wsgi:application"
    postDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
